a = int(input('Enter the first value'))
b = int(input('Enter the first value'))
print ('addition')
print (a+b)
print ('substraction')
print (a-b)
print ('multiplication')
print (a*b)
print ('division')
print (a/b)
